name: project
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.0.9
  provider: ^6.1.2
  cupertino_icons: ^1.0.2
  firebase_core: ^2.30.1
  firebase_database: ^10.5.2
  firebase_auth: ^4.19.4
  cloud_firestore: ^4.17.2
  firebase_storage: ^11.7.0
  firebase_auth_web: ^5.11.4
  flutter_vibrate: ^1.3.0
  audioplayers: ^6.0.0
  geolocator: ^7.0.3
  google_maps_flutter: ^2.0.10
  google_maps_webservice: ^0.0.15
  
  

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  


dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^3.0.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:


    # - C:\Users\hibat\Desktop\care_pat\project\assets\images\img_rectangle_1.png
    # - C:\Users\hibat\Desktop\care_pat\project\assets\images\fall.png

    # - C:\Users\user\care_pat\project\assets\images\op.jpg
    # - C:\Users\user\care_pat\project\assets\images\fall.png
    




    # - C:\Users\hibat\Desktop\care_pat\project\assets\images\img_rectangle_1.png
    # - C:\Users\hibat\Desktop\care_pat\project\assets\images\fall.png

    # - C:\Users\IT Dept\Desktop\care_pat\project\assets\images

  
        
    #- C:\Users\user\care_pat\project\assets\images\op.jpg
    #- C:\Users\user\care_pat\project\assets\images\fall.png

# Hiba"s
    # - C:\Users\hibat\Desktop\care_pat\project\assets\images\img_rectangle_1.png
    # - C:\Users\hibat\Desktop\care_pat\project\assets\images\fall.png

    # - C:\Users\hibat\Desktop\care_pat\project\assets\images\op.jpg
    # - C:\Users\hibat\Desktop\care_pat\project\assets\alarm-beep.mp3
    # - C:\Users\hibat\Desktop\care_pat\project\assets\images\logo.png
# christina"s
    #- C:\Users\user\care_pat\project\assets\images\op.jpg
    #- C:\Users\user\care_pat\project\assets\images\fall.png
    

    # - C:\Users\user\care_pat\project\assets\images\img_rectangle_1.png
    # - C:\Users\user\care_pat\project\assets\images\fall.png
    # - C:\Users\user\care_pat\project\assets\images\op.jpg
    # - C:\Users\user\care_pat\project\assets\alarm-beep.mp3
    # - C:\Users\user\care_pat\project\assets\images\logo.png

        #Sneha's:
    # - C:\Users\IT Dept\Desktop\care_pat\project\assets\images\img_rectangle_1.png
    # - C:\Users\IT Dept\Desktop\care_pat\project\assets\images\fall.png
    - C:\Users\IT Dept\Desktop\care_pat\project\assets\images\img_rectangle_1.png
    - C:\Users\IT Dept\Desktop\care_pat\project\assets\images\fall.png
    - C:\Users\IT Dept\Desktop\care_pat\project\assets\images\op.jpg
    - C:\Users\IT Dept\Desktop\care_pat\project\assets\alarm-beep.mp3
    - C:\Users\IT Dept\Desktop\care_pat\project\assets\images\logo.png

    # - C:\Users\IT Dept\Desktop\care_pat\project\assets\images\

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  fonts:
  - family: Inika
    fonts:
      - asset: assets/fonts/Inika.ttf
      - asset: assets/fonts/InikaBold.ttf
        weight: 700
  - family: Poppins
    fonts:
      
      - asset: assets/fonts/Poppins-Thin.ttf
      - asset: assets/fonts/Poppins-Regular.ttf

  - family: Pacifico
    fonts:
      - asset: assets/fonts/Pacifico.ttf
        weight: 700
  - family: Jersey20
    fonts:
      - asset: assets/fonts/Jersey20-Regular.ttf
      
        weight: 700
  - family: Abel
    fonts:
      - asset: assets/fonts/Abel-Regular.ttf

  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
